## Circleator config with both coverage tracks
small-cgap
## Inner coverage ring (Illumina, red)
new cov_illumina graph 0.14 graph-function=BAMCoverage,bam-file=chromosome.illumina.circleator.bam,bam-seqid=Limnothrix,graph-min=0,graph-max=data_max,window-size=5000,heightf=0.25,opacity=0.85,color1=#e41a1c

small-cgap
## Inner coverage ring (ONT, blue)
new cov_ont graph 0.14 graph-function=BAMCoverage,bam-file=chromosome.ont.circleator.bam,bam-seqid=Limnothrix,graph-min=0,graph-max=data_max,window-size=10000,heightf=0.25,opacity=0.85,color1=#3aa0d5
